# Generated by Django 4.2.6 on 2023-10-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submit",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pr_link",
                    models.URLField(
                        error_messages={
                            "invalid": "Enter a valid URL. e.g https://google.com"
                        },
                        max_length=2000,
                        verbose_name="pr link",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="The points value for the submitted PR",
                        verbose_name="points",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Submissions",
                "ordering": ["date_created"],
            },
        ),
    ]
